services:
  sqlserver:
    platform: linux/amd64
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: snapp-mssql
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "P@ssw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    volumes:
      - sqlvol:/var/opt/mssql
      - ./sql-scripts/init-database.sql:/docker-entrypoint-initdb.d/init-database.sql:ro
      - ./sql-scripts/entrypoint.sh:/usr/local/bin/entrypoint.sh:ro
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    networks:
      - vgsdemonet
    restart: unless-stopped


  tomcat:
    platform: linux/amd64
    image: tomcat:9.0-jdk8-temurin
    container_name: snapp-tomcat
    environment:
      CATALINA_OPTS: "-Xms4g -Xmx8g -Xloggc:gc.log -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintHeapAtGC"
      DBPASSWORD: "P@ssw0rd"
    ports:
      - "8080:8080"
    volumes:
      - tomcatvol:/usr/local/tomcat
    depends_on:
      - sqlserver
    networks:
      - vgsdemonet
    restart: unless-stopped

  jenkins:
    platform: linux/amd64
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    container_name: snapp-jenkins
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins/jobs:/var/jenkins_home/jobs
      - .:/workspace
      - ./jenkins/ssh:/root/.ssh:ro
    user: root
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - JENKINS_OPTS=--httpPort=8080
    networks:
      - vgsdemonet
    restart: unless-stopped


networks:
  vgsdemonet:
    driver: bridge


volumes:
  sqlvol:
    name: sqlvol
  tomcatvol:
    name: tomcatvol
  jenkins_home:
    name: jenkins_home