<%@page import="com.vgs.snapp.dataobject.*"%>
<%@page import="com.vgs.cl.lookup.*"%>
<%@page import="com.vgs.snapp.library.*"%>
<%@page import="com.vgs.web.tag.*"%>
<%@page import="com.vgs.cl.document.*"%>
<%@page import="com.vgs.web.page.*"%>
<%@page import="com.vgs.service.dataobject.*"%>
<%@page import="com.vgs.web.library.*"%>
<%@page import="com.vgs.cl.*"%> 
<%@page import="com.vgs.snapp.lookup.*"%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="vgs-tags" prefix="v" %>
<%@ taglib uri="rgt-tags" prefix="rgt" %>

<jsp:useBean id="pageBase" class="com.vgs.snapp.web.common.page.PageCommonWidget" scope="request"/>
<jsp:useBean id="rightsEnt" class="com.vgs.snapp.dataobject.DORightRoot" scope="request"/>
<jsp:useBean id="rightsDef" class="com.vgs.snapp.dataobject.DORightRoot" scope="request"/>
<jsp:useBean id="rightsUI" class="com.vgs.snapp.dataobject.DORightDialogUI" scope="request"/>
<jsp:useBean id="rights" class="com.vgs.snapp.dataobject.DORightRoot" scope="request"/>

<rgt:menu-content id="rights-menu-doctemplate">
<% if (rightsEnt.EntityType.isLookup(rightsUI.WksEntities.getLkArray())) { %>
  <rgt:section>
    <rgt:combo rightType="<%=LkSNRightType.SecondLangISO%>"/>
    <rgt:bool rightType="<%=LkSNRightType.AutomatcReceiptCut%>"/>
    <rgt:bool rightType="<%=LkSNRightType.AutomaticCutAllTickets%>"/>
  </rgt:section>

  <rgt:section caption="@DocTemplate.TrnReceipt">
    <rgt:combo rightType="<%=LkSNRightType.TrnReceipt_DocTemplateId%>"/>
    <rgt:combo rightType="<%=LkSNRightType.TrnPaymentReceipt_DocTemplateId%>"/>
    <rgt:combo rightType="<%=LkSNRightType.TrnReceiptKioskFailure_DocTemplateId%>"/>
    <rgt:combo rightType="<%=LkSNRightType.GiftReceipt_DocTemplateId%>"/>
    <rgt:bool rightType="<%=LkSNRightType.TrnReceiptOnDemandOnly%>"/>
    <rgt:multi rightType="<%=LkSNRightType.TrnReceiptDoublePrintProductTags%>"/>
    <rgt:multi rightType="<%=LkSNRightType.TrnReceiptDoublePrintPromoTags%>"/>
    <rgt:multi rightType="<%=LkSNRightType.TrnReceiptIgnoreTrnType%>" inline="false"/>
    <rgt:bool rightType="<%=LkSNRightType.TrnReceiptSettleConsolidate%>"/>
    <rgt:area rightType="<%=LkSNRightType.TrnReceiptHeader%>"/>
    <rgt:area rightType="<%=LkSNRightType.TrnReceiptAlreadyPrinted%>"/>
    <rgt:bool rightType="<%=LkSNRightType.TrnReceiptFailureShowAbort%>"/>
    <rgt:bool rightType="<%=LkSNRightType.TrnReceiptPrintUpgradeSourceItem%>"/>
    <rgt:bool rightType="<%=LkSNRightType.TrnReceiptPrintRenewSourceItem%>"/>
  </rgt:section>
  
  <rgt:section caption="@DocTemplate.CustomTransactionTypeReceipt">
    <rgt:combo rightType="<%=LkSNRightType.GiftCardActivateReceipt_DocTemplateId%>"/>
    <rgt:combo rightType="<%=LkSNRightType.GiftCardReloadReceipt_DocTemplateId%>"/>
    <rgt:combo rightType="<%=LkSNRightType.GiftCardCashoutReceipt_DocTemplateId%>"/>
  </rgt:section>
  
  <rgt:section caption="@Common.Default">
    <rgt:combo rightType="<%=LkSNRightType.Product_DocTemplateId%>"/>
    <rgt:bool rightType="<%=LkSNRightType.PahMediaActive%>"/>
  </rgt:section>

  <rgt:section caption="@Right.AutoGenerateDocs_Title">
    <rgt:bool rightType="<%=LkSNRightType.AutoGenDoc_StraightSale%>"/>
  </rgt:section>

  <rgt:section caption="PDF">
    <rgt:bool rightType="<%=LkSNRightType.MultipleMediaPerPage%>"/>
    <rgt:subset>
      <rgt:text rightType="<%=LkSNRightType.MediaTemplateMarginTop%>"/>
      <rgt:text rightType="<%=LkSNRightType.MediaTemplateMarginRight%>"/>
      <rgt:text rightType="<%=LkSNRightType.MediaTemplateMarginBottom%>"/>
      <rgt:text rightType="<%=LkSNRightType.MediaTemplateMarginLeft%>"/>
      <rgt:text rightType="<%=LkSNRightType.MarginBetweenMedias%>"/>
      <rgt:bool rightType="<%=LkSNRightType.DocPdfDisplaySnappWatermark%>"/>
      <rgt:bool rightType="<%=LkSNRightType.DocPdfDisplaySnappOnFooter%>"/>
    </rgt:subset>
  </rgt:section>

  <rgt:section caption="@Reservation.BatchPrinting">
    <rgt:combo rightType="<%=LkSNRightType.ResBatch_DocTemplateId%>"/>
  </rgt:section>
  
  <rgt:section>
    <rgt:multi rightType="<%=LkSNRightType.ExternalMediaTemplates%>" inline="false"/>
  </rgt:section>

  <rgt:section caption="@Box.BoxMaintenance">
    <rgt:combo rightType="<%=LkSNRightType.BoxFinalReceipt_DocTemplateId%>"/>
    <rgt:combo rightType="<%=LkSNRightType.BoxDepositReceipt_DocTemplateId%>"/>
    <rgt:combo rightType="<%=LkSNRightType.BoxExpectedAmountsReceipt_DocTemplateId%>"/>
    <rgt:area rightType="<%=LkSNRightType.BoxReceiptHeader%>"/>
    <rgt:bool rightType="<%=LkSNRightType.BoxReceiptAskForReprint%>"/>
    <rgt:bool rightType="<%=LkSNRightType.BoxReceiptFailureShowAbort%>"/>
    <rgt:multi rightType="<%=LkSNRightType.FinalCloseReceiptRestrictPaymentIDs%>"/>
    <rgt:multi rightType="<%=LkSNRightType.DepositReceiptRestrictPaymentIDs%>"/>
    <rgt:multi rightType="<%=LkSNRightType.WithdrawalReceiptRestrictPaymentIDs%>"/>
  </rgt:section>
  
  <rgt:section caption="@DocTemplate.OtherReceipts">
    <rgt:combo rightType="<%=LkSNRightType.WalletReceipt_DocTemplateId%>"/>
    <rgt:combo rightType="<%=LkSNRightType.IntercompanyReceipt_DocTemplateId%>"/>
    <rgt:subset>
      <rgt:bool rightType="<%=LkSNRightType.IntercompanyReceiptAskForReprint%>"/>
    </rgt:subset>
    <rgt:combo rightType="<%=LkSNRightType.GiftCardLookupReceipt_DocTemplateId%>"/>
    <rgt:combo rightType="<%=LkSNRightType.PortfolioSlotLog_DocTemplateId%>"/>
  </rgt:section>
  
  <rgt:section caption="@Right.AccountProfile">
    <rgt:combo rightType="<%=LkSNRightType.ForgotPassword_DocTemplateId%>"/>
    <rgt:combo rightType="<%=LkSNRightType.EmailVerification_DocTemplateId%>"/>
  </rgt:section>
  
  <% if (rightsEnt.EntityType.isLookup(LkSNEntityType.Licensee)) { %>
    <rgt:section caption="@Right.CSV_Excel">
      <rgt:text rightType="<%=LkSNRightType.CSV_EscapeChars%>"/>
    </rgt:section>
  <% } %>
  
  <rgt:section caption="@Right.OrderDispatch">
    <% if (rightsEnt.EntityType.isLookup(LkSNEntityType.Workstation)) { %>
      <rgt:multi rightType="<%=LkSNRightType.RecSpooler_DocTemplateIDs%>"/>
      <rgt:multi rightType="<%=LkSNRightType.RecSpooler_OpAreaIDs%>" inline="false"/>
      <rgt:bool rightType="<%=LkSNRightType.RecSpooler_FullPrintOnPayment%>"/>
      <rgt:text rightType="<%=LkSNRightType.RecSpooler_ThreadFreq%>"/>
    <% } %>
    <rgt:bool rightType="<%=LkSNRightType.RecSpooler_DifferentialPrint%>"/>
  </rgt:section>
    
  <% if (rightsEnt.EntityType.isLookup(LkSNEntityType.Workstation)) { %>
    <rgt:section caption="@Right.DeferredMediaPrint">
      <rgt:bool rightType="<%=LkSNRightType.AllowDeferredMediaPrint%>"/>
      <rgt:multi rightType="<%=LkSNRightType.DeferredMediaPrint_DocTemplateIDs%>"/>
      <rgt:multi rightType="<%=LkSNRightType.DeferredMediaPrint_OpAreaIDs%>" inline="false"/>
      <rgt:text rightType="<%=LkSNRightType.DeferredMediaPrint_ThreadFreq%>"/>
    </rgt:section>
  <% } %>
  
  <% if (rightsEnt.EntityType.isLookup(LkSNEntityType.Licensee)) { %>
    <rgt:section caption="@Common.PayByLink">
      <rgt:combo rightType="<%=LkSNRightType.PayByLink_RecapOrder_DocTemplateId%>"/>
      <rgt:combo rightType="<%=LkSNRightType.PayByLink_404_DocTemplateId%>"/>
      <rgt:combo rightType="<%=LkSNRightType.PayByLink_500_DocTemplateId%>"/>
      <rgt:combo rightType="<%=LkSNRightType.PayByLink_InvalidToken_DocTemplateId%>"/>
      <rgt:combo rightType="<%=LkSNRightType.PayByLink_AlreadyPaid_DocTemplateId%>"/>
      <rgt:combo rightType="<%=LkSNRightType.PayByLink_PaymentDone_DocTemplateId%>"/>
    </rgt:section>
  <% } %> 
  
  <rgt:section caption="@Common.Other">
    <% if (rightsEnt.EntityType.isLookup(LkSNEntityType.Licensee)) { %>
      <rgt:combo rightType="<%=LkSNRightType.MobileWalletTicketTemplateId%>"/>
      <rgt:combo rightType="<%=LkSNRightType.MobileWalletSaleTemplateId%>"/>
      <rgt:combo rightType="<%=LkSNRightType.EmailVerifSuccessLandingPageTemplateId%>"/>
      <rgt:combo rightType="<%=LkSNRightType.EmailVerifFailureLandingPageTemplateId%>"/>
      <rgt:combo rightType="<%=LkSNRightType.ResetPwdSuccessLandingPageTemplateId%>"/>
      <rgt:combo rightType="<%=LkSNRightType.ResetPwdFailureLandingPageTemplateId%>"/>
    <% } %> 
    <rgt:combo rightType="<%=LkSNRightType.AccountTempPageTemplateId%>"/>
  </rgt:section>

<% } %>
</rgt:menu-content>
